// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title X402PaymentGateway
 * @author AIFoundry.sh
 * @notice Production-grade, multi-chain payment settlement gateway for x402 HTTP micropayments.
 * Supports ERC20 (USDC/USDT), native GAS token payments, gasless EIP-712 signature verification,
 * and instant beneficiary routing.
 */

interface IERC20 {
    function totalSupply() external view returns (uint256);
    function balanceOf(address account) external view returns (uint256);
    function transfer(address recipient, uint256 amount) external returns (bool);
    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 amount) external returns (bool);
    function transferFrom(address sender, address recipient, uint256 amount) external returns (bool);
}

interface IERC20Permit {
    function permit(
        address owner,
        address spender,
        uint256 value,
        uint256 deadline,
        uint8 v,
        bytes32 r,
        bytes32 s
    ) external;
}

contract X402PaymentGateway {
    // Beneficiary treasury address that receives funds directly
    address public beneficiary;
    // Gateway owner / administrator
    address public owner;
    
    // Whitelisted accepted token contracts (e.g. USDC, USDT)
    mapping(address => bool) public acceptedTokens;
    // Used nonces for off-chain EIP-712 request verification
    mapping(bytes32 => bool) public usedNonces;

    // Events
    event PaymentSettled(
        bytes32 indexed requestId,
        address indexed payer,
        address indexed token,
        uint256 amountUsd6,
        uint256 timestamp
    );
    event BeneficiaryUpdated(address indexed oldBeneficiary, address indexed newBeneficiary);
    event TokenWhitelistUpdated(address indexed token, bool status);

    modifier onlyOwner() {
        require(msg.sender == owner, "X402: caller is not owner");
        _;
    }

    /**
     * @dev Initialize gateway with beneficiary treasury address
     * @param _beneficiary Beneficiary wallet address (e.g. 0x003cC678764C8143a4b92370acB40e3B41319016)
     */
    constructor(address _beneficiary) {
        require(_beneficiary != address(0), "X402: invalid beneficiary address");
        owner = msg.sender;
        beneficiary = _beneficiary;
    }

    /**
     * @notice Pay for an x402 API call directly using an ERC20 token (USDC / USDT)
     * @param requestId Unique request hash generated by x402 client
     * @param token Address of the accepted ERC20 token (USDC)
     * @param amount Token amount to transfer (e.g. 50000 for $0.05 USDC with 6 decimals)
     */
    function payForCall(bytes32 requestId, address token, uint256 amount) external returns (bool) {
        require(!usedNonces[requestId], "X402: request ID already settled");
        require(acceptedTokens[token] || token != address(0), "X402: token not whitelisted");
        require(amount > 0, "X402: payment amount must be > 0");

        usedNonces[requestId] = true;

        bool success = IERC20(token).transferFrom(msg.sender, beneficiary, amount);
        require(success, "X402: ERC20 transfer failed");

        emit PaymentSettled(requestId, msg.sender, token, amount, block.timestamp);
        return true;
    }

    /**
     * @notice Pay for an x402 API call using Native EVM Gas Token (ETH / POL / CELO)
     * @param requestId Unique request hash generated by x402 client
     */
    function payForCallNative(bytes32 requestId) external payable returns (bool) {
        require(!usedNonces[requestId], "X402: request ID already settled");
        require(msg.value > 0, "X402: payment amount must be > 0");

        usedNonces[requestId] = true;

        (bool sent, ) = payable(beneficiary).call{value: msg.value}("");
        require(sent, "X402: Native transfer failed");

        emit PaymentSettled(requestId, msg.sender, address(0), msg.value, block.timestamp);
        return true;
    }

    /**
     * @notice Pay for an x402 API call via EIP-2612 Gasless Permit signature
     * @param requestId Unique request hash generated by x402 client
     * @param token USDC token contract supporting permit
     * @param amount Amount to transfer
     * @param deadline Signature expiry deadline
     * @param v Permit signature v
     * @param r Permit signature r
     * @param s Permit signature s
     */
    function payWithPermit(
        bytes32 requestId,
        address token,
        uint256 amount,
        uint256 deadline,
        uint8 v,
        bytes32 r,
        bytes32 s
    ) external returns (bool) {
        require(!usedNonces[requestId], "X402: request ID already settled");

        usedNonces[requestId] = true;

        // Execute permit approval
        IERC20Permit(token).permit(msg.sender, address(this), amount, deadline, v, r, s);

        // Execute transfer directly to treasury
        bool success = IERC20(token).transferFrom(msg.sender, beneficiary, amount);
        require(success, "X402: Permit transfer failed");

        emit PaymentSettled(requestId, msg.sender, token, amount, block.timestamp);
        return true;
    }

    /**
     * @notice Whitelist or remove an accepted ERC20 payment token
     */
    function setAcceptedToken(address token, bool status) external onlyOwner {
        acceptedTokens[token] = status;
        emit TokenWhitelistUpdated(token, status);
    }

    /**
     * @notice Update the treasury beneficiary address
     */
    function setBeneficiary(address newBeneficiary) external onlyOwner {
        require(newBeneficiary != address(0), "X402: invalid beneficiary");
        emit BeneficiaryUpdated(beneficiary, newBeneficiary);
        beneficiary = newBeneficiary;
    }

    /**
     * @notice Emergency sweep in case tokens were accidentally transferred to contract
     */
    function emergencySweep(address token) external onlyOwner {
        if (token == address(0)) {
            payable(beneficiary).transfer(address(this).balance);
        } else {
            uint256 balance = IERC20(token).balanceOf(address(this));
            IERC20(token).transfer(beneficiary, balance);
        }
    }
}
